# Generated by Django 6.0.7 on 2026-07-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('meeting', 'Meeting'), ('call', 'Phone Call'), ('email', 'Email'), ('other', 'Other')], default='meeting', max_length=20)),
                ('summary', models.TextField()),
                ('structured_data', models.JSONField(default=dict)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('action_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='hcp.hcp')),
            ],
        ),
    ]
